
package org.regenstrief.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DumpService", targetNamespace = "http://www.regenstrief.org/services", wsdlLocation = "file:/C:/Users/msheley/git/chica/MRNRequestForDump.wsdl")
public class DumpService
    extends Service
{

    private final static URL DUMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException DUMPSERVICE_EXCEPTION;
    private final static QName DUMPSERVICE_QNAME = new QName("http://www.regenstrief.org/services", "DumpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/msheley/git/chica/MRNRequestForDump.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DUMPSERVICE_WSDL_LOCATION = url;
        DUMPSERVICE_EXCEPTION = e;
    }

    public DumpService() {
        super(__getWsdlLocation(), DUMPSERVICE_QNAME);
    }

    public DumpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DUMPSERVICE_QNAME, features);
    }

    public DumpService(URL wsdlLocation) {
        super(wsdlLocation, DUMPSERVICE_QNAME);
    }

    public DumpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DUMPSERVICE_QNAME, features);
    }

    public DumpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DumpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDumpService
     */
    @WebEndpoint(name = "GetDump")
    public IDumpService getGetDump() {
        return super.getPort(new QName("http://www.regenstrief.org/services", "GetDump"), IDumpService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDumpService
     */
    @WebEndpoint(name = "GetDump")
    public IDumpService getGetDump(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.regenstrief.org/services", "GetDump"), IDumpService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DUMPSERVICE_EXCEPTION!= null) {
            throw DUMPSERVICE_EXCEPTION;
        }
        return DUMPSERVICE_WSDL_LOCATION;
    }

}
