
package org.regenstrief.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IDumpService", targetNamespace = "http://www.regenstrief.org/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDumpService {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.regenstrief.services.GetDumpResponse
     */
    @WebMethod
    @WebResult(name = "getDumpResponse", targetNamespace = "http://www.regenstrief.org/services", partName = "parameters")
    public GetDumpResponse getDump(
        @WebParam(name = "getDump", targetNamespace = "http://www.regenstrief.org/services", partName = "parameters")
        GetDump parameters);

}
