LOAD DATA LOCAL INFILE 'C:/CHICA_1.0_DATA/chica1_appointments.csv'
    IGNORE
INTO TABLE chica1_appointments
   FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
   LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'C:/CHICA_1.0_DATA/chica1_patient.csv'
    IGNORE
INTO TABLE chica1_patient
   FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
   LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'C:/CHICA_1.0_DATA/chica1_patient_obsv.csv'
    IGNORE
INTO TABLE chica1_patient_obsv
   FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
   LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'C:/CHICA_1.0_DATA/chica1_obsv_dictionary.csv'
    IGNORE
INTO TABLE chica1_obsv_dictionary
   FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
   LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'C:/CHICA_1.0_DATA/vitals_obsv_dictionary.csv'
    IGNORE
INTO TABLE chica1_obsv_dictionary
   FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
   LINES TERMINATED BY '\r\n';
