version: 2
updates:

   - package-ecosystem: "maven"
     directory: "/"
     schedule:
        interval: "weekly"
        day: "thursday"
        time: "07:45"
        timezone: "America/Indiana/Indianapolis"
     target-branch: "Prod_Release_18.0"
     open-pull-requests-limit: 0